module.exports = {
    content: ["./Views/**/*.{cshtml, html,js}"],
    theme: {
        extend: {},
    },
    plugins: [require('@tailwindcss/forms')],
    safelist: [
        'cursor-pointer',
        'cursor-not-allowed',
        'bg-slate-900',
        'bg-slate-800',
        'bg-slate-700',
        'bg-slate-600',
        'bg-slate-500',
        'bg-slate-400',
        'bg-slate-200',
        'bg-green-500',
        'bg-green-200',
        'before:absolute',
        'after:absolute',
        'before:-top-12',
        'before:right-0',
        'before:h-12',
        'before:w-12',
        'before:rounded-br-2xl',
        'before:shadow-[0_1rem_0_0_rgba(15,23,42,1)]',
        'before:shadow-slate-900',
        'after:-bottom-12',
        'after:right-0',
        'after:h-12',
        'after:w-12',
        'after:rounded-tr-2xl',
        'after:shadow-[0_-1rem_0_0_rgba(15,23,42,1)]',
        'after:shadow-slate-900',
        'border-t-2',
        'border-green-500',
        'hover:bg-green-400',
        'bg-gray-200',
        'bg-gray-600',
        'h-2.5',
        'dark:bg-gray-300',
        'w-1/5',
        'w-2/5',
        'w-3/5',
        'w-4/5'
    ]
}
