# this is a basic workflow to build a docker image and push it to docker hub
name: auto-tag

# controls when the action will run.
# triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [main]

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow contains a single job called "push_to_registry"
  auto-tag:
    # the type of runner that the job will run on
    runs-on: ubuntu-latest

    # permissions
    permissions:
      contents: write

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - name: checkout the repository
        uses: actions/checkout@v2

      # auto tag
      - name: bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
