# this is a basic workflow to auto tag on merge into main and then
# build a docker image and push it to docker hub
name: auto-tag-and-push-to-dockerhub

# controls when the action will run.
# triggers the workflow when a new tag is pushed
on:
  push:
    branches: [main]

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow contains one job, it tags the docker image and pushs it to docker hub
  push_to_registry:
    # the type of runner that the job will run on
    runs-on: ubuntu-latest

    # permissions
    permissions:
      contents: write

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - name: checkout the repository
        uses: actions/checkout@v4

      # auto tag
      - name: bump version and push tag
        id: tagger
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # set up qemu
      - name: set up qemu
        uses: docker/setup-qemu-action@v3

      # set up docker buildx
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      # login into docker hub
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # docker meta data
      - name: set up docker meta data
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bejebeje/admin
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.tagger.outputs.new_tag }}

      # build the docker image then push it to docker hub
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
